create extension if not exists pgcrypto;

create table if not exists public.tennis_players (
  id uuid primary key default gen_random_uuid(),
  provider_player_id text unique,
  tour text not null check (tour in ('ATP', 'WTA')),
  name text not null,
  country_code text,
  handedness text,
  birth_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tennis_matches (
  id uuid primary key default gen_random_uuid(),
  provider_match_id text unique,
  tour text not null check (tour in ('ATP', 'WTA')),
  tournament text not null,
  round text,
  surface text not null,
  indoor boolean not null default false,
  scheduled_at timestamptz not null,
  player_a_id uuid not null references public.tennis_players(id),
  player_b_id uuid not null references public.tennis_players(id),
  winner_id uuid references public.tennis_players(id),
  status text not null default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tennis_feature_snapshots (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.tennis_matches(id) on delete cascade,
  captured_at timestamptz not null,
  player_id uuid not null references public.tennis_players(id),
  ranking integer,
  elo numeric,
  surface_elo numeric,
  hold_pct numeric,
  break_pct numeric,
  form_score numeric,
  fatigue_score numeric,
  physical_risk numeric,
  data_quality numeric,
  feature_version text not null,
  unique (match_id, captured_at, player_id, feature_version)
);

create table if not exists public.tennis_odds_snapshots (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.tennis_matches(id) on delete cascade,
  bookmaker text not null,
  market text not null default 'moneyline',
  captured_at timestamptz not null,
  player_a_odds numeric not null check (player_a_odds > 1),
  player_b_odds numeric not null check (player_b_odds > 1),
  is_closing boolean not null default false
);

create table if not exists public.tennis_model_runs (
  id uuid primary key default gen_random_uuid(),
  model_name text not null,
  model_version text not null,
  trained_through date,
  validation_method text not null default 'walk-forward',
  brier_score numeric,
  log_loss numeric,
  roi numeric,
  avg_clv numeric,
  sample_size integer,
  artifact_uri text,
  created_at timestamptz not null default now()
);

create table if not exists public.tennis_predictions (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.tennis_matches(id) on delete cascade,
  model_run_id uuid references public.tennis_model_runs(id),
  odds_snapshot_id bigint references public.tennis_odds_snapshots(id),
  created_at timestamptz not null default now(),
  probability_a numeric not null check (probability_a between 0 and 1),
  probability_b numeric not null check (probability_b between 0 and 1),
  fair_odds_a numeric not null,
  fair_odds_b numeric not null,
  market_probability_a numeric,
  market_probability_b numeric,
  edge_a numeric,
  edge_b numeric,
  ev_a numeric,
  ev_b numeric,
  uncertainty numeric not null check (uncertainty between 0 and 1),
  recommendation text not null,
  tier text not null,
  stake_units numeric not null default 0,
  feature_version text not null
);

create table if not exists public.tennis_outcomes (
  match_id uuid primary key references public.tennis_matches(id) on delete cascade,
  settled_at timestamptz not null,
  winner_id uuid not null references public.tennis_players(id),
  retired boolean not null default false,
  walkover boolean not null default false,
  score text
);

create index if not exists idx_tennis_matches_schedule
  on public.tennis_matches (scheduled_at);

create index if not exists idx_tennis_odds_match_time
  on public.tennis_odds_snapshots (match_id, captured_at desc);

create index if not exists idx_tennis_features_match_time
  on public.tennis_feature_snapshots (match_id, captured_at desc);

create index if not exists idx_tennis_predictions_match
  on public.tennis_predictions (match_id, created_at desc);

alter table public.tennis_players enable row level security;
alter table public.tennis_matches enable row level security;
alter table public.tennis_feature_snapshots enable row level security;
alter table public.tennis_odds_snapshots enable row level security;
alter table public.tennis_model_runs enable row level security;
alter table public.tennis_predictions enable row level security;
alter table public.tennis_outcomes enable row level security;

-- No anon/authenticated policies are created in V1.
-- The application is server-side by default and must not expose the service role key.
