import type {Market,OddsEvent,Opportunity,Outcome} from "./types";
export const FRENCH_BOOKS=["betclic_fr","netbet_fr","pmu_fr","unibet_fr","winamax_fr"] as const;
export const REFERENCE_BOOK="pinnacle";
const pointKey=(p?:number)=>p==null?"none":String(p);
function groups(m:Market){const x=new Map<string,Outcome[]>();for(const o of m.outcomes){const k=pointKey(o.point);x.set(k,[...(x.get(k)??[]),o])}return x}
export function devig(outcomes:Outcome[]){const v=outcomes.filter(o=>Number.isFinite(o.price)&&o.price>1);if(v.length<2)return null;const raw=v.map(o=>({...o,implied:1/o.price}));const sum=raw.reduce((a,b)=>a+b.implied,0);if(sum<=1||sum>1.35)return null;return raw.map(o=>({...o,fairProbability:o.implied/sum,fairOdds:1/(o.implied/sum),overround:sum-1}))}
const same=(a:Outcome,b:Outcome)=>a.name===b.name&&pointKey(a.point)===pointKey(b.point);
const age=(ts?:string)=>ts?Math.max(0,(Date.now()-Date.parse(ts))/1000):9999;
function score(edge:number,seconds:number,overround:number){let s=60+Math.min(20,edge*250)-Math.max(0,seconds-60)*.08-Math.max(0,overround-.08)*120;return Math.max(0,Math.min(100,Math.round(s)))}
export function scanEvent(event:OddsEvent,minEdge=.025):Opportunity[]{const ref=event.bookmakers.find(b=>b.key===REFERENCE_BOOK);if(!ref)return[];const out:Opportunity[]=[];for(const rm of ref.markets){for(const ro of groups(rm).values()){const fair=devig(ro);if(!fair)continue;for(const book of event.bookmakers.filter(b=>FRENCH_BOOKS.includes(b.key as never))){const m=book.markets.find(x=>x.key===rm.key);if(!m)continue;for(const c of m.outcomes){const r=ro.find(o=>same(o,c)),f=fair.find(o=>same(o,c));if(!r||!f||c.price<=1)continue;const edge=f.fairProbability*c.price-1;if(edge<minEdge||edge>.25)continue;const ra=age(rm.last_update??ref.last_update),ba=age(m.last_update??book.last_update);if(ra>180||ba>180)continue;out.push({id:[event.id,rm.key,c.name,pointKey(c.point),book.key].join(":"),eventId:event.id,sport:event.sport_title,event:`${event.home_team} — ${event.away_team}`,commenceTime:event.commence_time,market:rm.key,selection:c.name,point:c.point??null,bookmaker:book.key,bookmakerTitle:book.title,offeredOdds:c.price,referenceOdds:r.price,fairOdds:f.fairOdds,fairProbability:f.fairProbability,edge,confidence:score(edge,Math.max(ra,ba),f.overround),reference:REFERENCE_BOOK,referenceUpdatedAt:rm.last_update??ref.last_update??null,bookmakerUpdatedAt:m.last_update??book.last_update??null})}}}}return out.sort((a,b)=>b.edge-a.edge||b.confidence-a.confidence)}
